### PR TITLE
Travis images already include composer self-upgrade

### PR DESCRIPTION
**Pull request by szepeviktor**
See https://travis-ci.org/imliam/laravel-blade-helper/jobs/583670791#L224

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could it be that you ditched Travis for GitHub Actions?

**Comment by szepeviktor** [comment]
GitHub Actions run PHp 7.2 & 7.3 BUT! https://github.com/imliam/laravel-blade-helper/blob/master/composer.json#L19

**Comment by imliam** [comment]
I'm definitely considering moving the CI to GitHub Actions - keeping both the configs here for the meantime to experiment while Actions is in beta.

Thanks for pointing out this line can be gone!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
